export const signIn = "Sign In";
export const signUp = "Sign Up";
export const needHelpLabel = "Need Help?";
export const validEmail = "Not a valid Email";
export const validPassword = "Not a valid Password";
export const validName = "Not a valid Full Name";
export const rememberMeLabel = "Remember Me";
export const signInLabel = "New to Netflix? Sign-up now.";
export const signUpLabel = "Already Registered? Sign In Now";
export const emailRegex = /^[\w\-\.]+@([\w-]+\.)+[\w-]{2,4}$/;
export const passwordRegex = /^(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{6,20}$/;
export const nameRegex = /\b([A-ZÀ-ÿ][-,a-z. ']+[ ]*)+/;
